site_name: The SILOE Project
site_url: https://siloe-project.com
site_description: |
  Scientists have pointed some of the most advanced technology towards the heavens in the search for intelligent life on other planets.  So far, however, there is little evidence of intelligence even here on Earth.  This website serves as a chronicle of the brave men and women who hope to someday find such intelligence.  The search continues...
repo_url: https://github.com/siloe-project/siloe-project.github.io
edit_uri: edit/main/docs/
theme:
  name: material
  # custom_dir: custom_theme/
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - toc.follow    
    - navigation.top
    - content.action.edit

markdown_extensions:
  - attr_list #add attributes using curly brackets to images, see https://squidfunk.github.io/mkdocs-material/reference/images/
  - md_in_html # see https://squidfunk.github.io/mkdocs-material/reference/images/
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tilde: {}


#must use ```pip install mkdocs-glightbox```

plugins:
  - glightbox # allow resize images, see https://squidfunk.github.io/mkdocs-material/reference/images/
  - rss

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    
    
copyright: Copyright &copy; 2024 Dan Aukes

extra:
  generator: false